"""Reporting utilities - CSV and HTML export.

This module extracts reporting logic from the main screener to keep
nifty_bearnness_v2.py focused on the core screening logic.
"""

import csv
import pandas as pd
from pathlib import Path
from datetime import datetime


def save_csv(results, output_path, args):
    """Save screening results to CSV with metadata."""
    if not results:
        print("[WARN] No results to save")
        return
    
    # Get universe
    from core.universe import UniverseManager
    universe_manager = UniverseManager()
    symbols = universe_manager.get_universe(args.universe)
    processed_count = len(results)
    skipped_count = len(symbols) - processed_count
    
    # Write CSV
    try:
        with open(output_path, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=results[0].keys() if results else [])
            writer.writeheader()
            writer.writerows(results)
        
        print(f"\n[OK] Saved {processed_count} results to {output_path}")
        print(f"[INFO] Skipped: {skipped_count} (no data)")
        
        return output_path
    except Exception as e:
        print(f"[ERROR] Failed to save CSV: {e}")
        return None


def save_html_simple(results, output_path, args):
    """Save results to simple HTML table."""
    if not results:
        print("[WARN] No results to save")
        return
    
    try:
        df = pd.DataFrame(results)
        
        # Basic HTML
        html = f"""
<html>
<head>
    <title>Bearness Screening Results - {args.universe.upper()} ({args.mode})</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #333; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th {{ background: #4CAF50; color: white; padding: 10px; text-align: left; }}
        td {{ padding: 8px; border-bottom: 1px solid #ddd; }}
        tr:hover {{ background: #f5f5f5; }}
        .positive {{ color: green; font-weight: bold; }}
        .negative {{ color: red; font-weight: bold; }}
    </style>
</head>
<body>
    <h1>Bearness Screening Results</h1>
    <p><strong>Universe:</strong> {args.universe.upper()} | <strong>Mode:</strong> {args.mode} | <strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    <p><strong>Total Stocks Analyzed:</strong> {len(results)}</p>
    
    {df.to_html(index=False, border=0)}
    
    <hr>
    <p><small>Generated by Bearness Screener v2</small></p>
</body>
</html>
        """
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
        
        print(f"[OK] Saved HTML report to {output_path}")
        return output_path
        
    except Exception as e:
        print(f"[ERROR] Failed to save HTML: {e}")
        return None


def print_results_summary(results, mode='swing'):
    """Print summary of results to console."""
    if not results:
        print("\n[WARN] No results to display")
        return
    
    print("\n" + "="*80)
    print(f"SCREENING RESULTS ({len(results)} stocks analyzed)")
    print("="*80)
    
    # Find top bearish and bullish
    sorted_results = sorted(results, key=lambda x: float(x.get('score', 0)))
    
    print("\n[TOP BEARISH - Most Negative]")
    for r in sorted_results[:5]:
        symbol = r.get('symbol', 'N/A')
        score = float(r.get('score', 0))
        conf = int(r.get('confidence', 0))
        print(f"  {symbol:12} Score: {score:7.3f} | Confidence: {conf:3d}%")
    
    print("\n[TOP BULLISH - Most Positive]")
    for r in sorted_results[-5:]:
        symbol = r.get('symbol', 'N/A')
        score = float(r.get('score', 0))
        conf = int(r.get('confidence', 0))
        print(f"  {symbol:12} Score: {score:7.3f} | Confidence: {conf:3d}%")
    
    print("\n" + "="*80)
